targets:
    $default:
        builders:
            ferry_generator|graphql_builder:
                enabled: true
                options:
                    schemas:
                        - flutter_controls_core|lib/src/service/acsys/schema/DPM.graphql
                        - flutter_controls_core|lib/src/service/devdb/schema/DEVDB.graphql
                    type_overrides:
                        Timestamp:
                            name: DateTime
            ferry_generator|serializer_builder:
                enabled: true
                options:
                    schemas:
                        - flutter_controls_core|lib/src/service/acsys/schema/DPM.graphql
                        - flutter_controls_core|lib/src/service/devdb/schema/DEVDB.graphql
                    custom_serializers:
                        - import: "package:flutter_controls_core/src/service/date_serializer.dart"
                          name: DateSerializer