name: flutter_controls_core
description: A Flutter package to write Fermilab applications.
version: 1.0.0
publish_to: none

environment:
    sdk: ">=3.10.0 <4.0.0"
    flutter: ">=3.27.0"

dependencies:
    flutter:
        sdk: flutter

    # One of our app types uses the GoRouter widget, so we need to include this
    # package.

    go_router: ^12.1.0

    opentelemetry: ^0.18.10

    # Needed for KeyCloak authentication support.

    flutter_controls_auth:
      git:
        url: https://github.com/fermi-ad/flutter-controls-auth.git
        ref: main

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^6.0.0
    analyzer: ^8.4.0

    test: ^1.24.3
    mocktail: ^1.0.4
    gql_exec: ^1.1.1-alpha+1699813812660

flutter:
    fonts:
      - family: Local Roboto
        fonts:
          - asset: assets/google_fonts/Roboto-Thin.ttf
            weight: 100
          - asset: assets/google_fonts/Roboto-ThinItalic.ttf
            weight: 100
            style: italic
          - asset: assets/google_fonts/Roboto-Light.ttf
            weight: 300
          - asset: assets/google_fonts/Roboto-LightItalic.ttf
            weight: 300
            style: italic
          - asset: assets/google_fonts/Roboto-Regular.ttf
          - asset: assets/google_fonts/Roboto-Italic.ttf
            style: italic
          - asset: assets/google_fonts/Roboto-Medium.ttf
            weight: 500
          - asset: assets/google_fonts/Roboto-MediumItalic.ttf
            weight: 500
            style: italic
          - asset: assets/google_fonts/Roboto-Bold.ttf
            weight: 700
          - asset: assets/google_fonts/Roboto-BoldItalic.ttf
            weight: 700
            style: italic
          - asset: assets/google_fonts/Roboto-Black.ttf
            weight: 900
          - asset: assets/google_fonts/Roboto-BlackItalic.ttf
            weight: 900
            style: italic
