name: flutter_controls_core
description: A Flutter package to write Fermilab applications.
version: 0.1.2
homepage:

environment:
    sdk: ">=3.1.0 <4.0.0"
    flutter: ">=1.17.0"

dependencies:
    flutter:
        sdk: flutter

    # These packages provide our GraphQL access.

    ferry: ^0.14.2+1
    ferry_flutter: ^0.8.1
    gql_http_link: ^1.0.1
    gql_websocket_link: ^2.0.0
    gql_code_builder: ^0.8.0
    web_socket_channel: ^2.4.0
    built_collection: ^5.1.1
    built_value: ^8.4.4

    # One of our app types uses the GoRouter widget, so we need to include this
    # package.

    go_router: ^12.1.0

    # Needed for KeyCloak authentication support.

    openid_client: ^0.4.8
    url_launcher: ^6.2.1

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^3.0.0
    analyzer: ^5.13.0

    ferry_generator: ^0.8.1
    build_runner: ^2.4.6
    test: ^1.24.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

    # To add assets to your package, add an assets section, like this:
    # assets:
    #   - images/a_dot_burr.jpeg
    #   - images/a_dot_ham.jpeg
    #
    # For details regarding assets in packages, see
    # https://flutter.dev/assets-and-images/#from-packages
    #
    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware

    # To add custom fonts to your package, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts in packages, see
    # https://flutter.dev/custom-fonts/#from-packages
