/// A Flutter package with resources that most Fermi applications need.
library;

import "package:flutter/material.dart";
import "package:flutter_controls_auth/flutter_controls_auth.dart";
import 'package:go_router/go_router.dart';
import 'src/app_scaffold.dart';
import 'src/otel_tracing.dart';

export 'src/status.dart';
export 'src/device_values.dart';
export 'src/app_scaffold.dart';
export 'package:flutter_controls_auth/flutter_controls_auth.dart'
    show ScopeList, AuthInfo, AuthService, Credential, UserInfo;

export 'src/service/acsys_service.dart';
export 'src/otel_tracing.dart' show AppTracer, appTracer, Span;
export 'package:bison_design_system/bison_design_system.dart';

/// Entry point for Fermilab applications
///
/// This function initializes the environment for the application as well as
/// creating a widget [Scaffold] that uses a standard color theme. It also
/// handles authentication with KeyCloak and sets up OpenTelemetry tracing.
///
/// - [appWidget] is the main widget that holds the body of the application.
/// - [authInfo] is an optional parameter which holds configuration information
///   for the application. Some of this info is generated by KeyCloak. If this
///   parameter is `null`, no credentials will be used (and most, if not all,
///   services won't let your application make modifications to the control
///   system.)
Future<void> runFermiApp({
  required Widget appWidget,
  AuthInfo? authInfo,
}) async {
  await initOpenTelemetry();
  if (authInfo != null) {
    await initAuth(authInfo);
  }
  return runApp(appWidget);
}

/// Entry point for Fermilab applications
///
/// This function initializes the environment, including a standard color scheme,
/// for an applicationthat uses the `go_router` package. It also handles
/// authentication with KeyCloak and sets up OpenTelemetry tracing.
///
/// - [appWidget] is the main widget that holds the body of the application.
/// - [authInfo] is an optional parameter which holds configuration information
///   for the application. Some of this info is generated by KeyCloak. If this
///   parameter is `null`, no credentials will be used (and most, if not all,
///   services won't let your application make modifications to the control
///   system.)
Future<void> runFermiRouterApp({
  required GoRouter router,
  AuthInfo? authInfo,
  required String title,
}) async {
  await initOpenTelemetry();
  if (authInfo != null) {
    await initAuth(authInfo);
    runApp(AuthRouterApp(title: title, router: router));
  } else {
    runApp(NonAuthRouterApp(title: title, router: router));
  }
}
