/// A Flutter package with resources that most Fermi applications need.
library;

import "package:flutter/material.dart";
import "package:flutter_controls_auth/flutter_controls_auth.dart";
import 'package:go_router/go_router.dart';
import 'src/app_scaffold.dart';
import 'src/otel_tracing.dart';

export 'src/app_scaffold.dart';
export 'package:flutter_controls_auth/flutter_controls_auth.dart'
    show AuthInfo, AuthService, Credential, UserInfo;

export 'src/otel_tracing.dart' show AppTracer, appTracer, Span;
export 'src/widgets/param_panel.dart' show ParameterPanel;
export 'src/widgets/param_row.dart' show ParameterPanelRow;
export 'package:bison_design_system/bison_design_system.dart';

/// Entry point for Fermilab applications
///
/// This function initializes the environment for the application as well as
/// creating a widget [Scaffold] that uses a standard color theme. It also
/// handles authentication with KeyCloak and sets up OpenTelemetry tracing.
///
/// - [appWidget] is the main widget that holds the body of the application.
/// - [authInfo] is an optional parameter which holds configuration information
///   for the application. Some of this info is generated by KeyCloak. If this
///   parameter is `null`, no credentials will be used (and most, if not all,
///   services won't let your application make modifications to the control
///   system.)
Future<void> runFermiApp({
  required Widget appWidget,
  AuthInfo? authInfo,
}) async {
  await initOpenTelemetry();
  if (authInfo != null) {
    await initAuth(authInfo);
  }
  return runApp(appWidget);
}

/// Entry point for Fermilab applications
///
/// This function initializes the environment, including a standard color scheme,
/// for an application that uses the `go_router` package. It also handles
/// authentication with KeyCloak and sets up OpenTelemetry tracing.
///
/// - [router] is the `GoRouter` instance that defines the application's
///   navigation structure.
/// - [title] is the title of the application, used for the web page title on
///   web targets.
/// - [authInfo] is an optional parameter which holds configuration information
///   for the application. Some of this info is generated by KeyCloak. If this
///   parameter is `null`, no credentials will be used (and most, if not all,
///   services won't let your application make modifications to the control
///   system.)
/// - [useBison] controls which design system theme is applied. When `true`,
///   the [BisonThemeData] theme is used. When `false` (default), the legacy
///   Fermi core theme is used.
Future<void> runFermiRouterApp({
  required GoRouter router,
  AuthInfo? authInfo,
  required String title,
  bool useBison = false,
}) async {
  await initOpenTelemetry();
  if (authInfo != null) {
    await initAuth(authInfo);
    runApp(AuthRouterApp(title: title, router: router, useBison: useBison));
  } else {
    runApp(NonAuthRouterApp(title: title, router: router, useBison: useBison));
  }
}
