/// A Flutter package with resources that most Fermi applications need.
library;

import "package:flutter/material.dart";
import "src/auth_widget.dart";
import 'package:go_router/go_router.dart';
import 'src/app_scaffold.dart';

export 'src/status.dart';
export 'src/device_values.dart';
export 'src/app_scaffold.dart';
export 'src/auth_widget.dart' show ScopeList, AuthInfo, AuthService;

export 'src/service/acsys_service.dart';

export 'package:openid_client/openid_client.dart' show Credential, UserInfo;

/// Entry point for Fermilab applications
///
/// This function intializes the environment for the application as well as
/// creating a widget [Scaffold] that uses a standard color theme. It also
/// handles authentication with KeyCloak.
///
/// - [appWidget] is the main widget that holds the body of the application.
/// - [authInfo] is an optional parameter which holds configuration information
///   for the application. Some of this info is generated by KeyCloak. If this
///   parameter is `null`, no credentials will be used (and most, if not all,
///   services won't let your application make modifications to the control
///   system.)

Future<void> runFermiApp({
  required Widget appWidget,
  AuthInfo? authInfo,
  GoRouter? router,
}) async {
  if (authInfo != null) {
    await initAuth(
      authInfo.realm,
      authInfo.clientId,
      authInfo.clientSecret,
      authInfo.scopes,
    );
  }
   //zyuan added this to avoid the error when using the fake services
  if (router != null) {
    runApp(
      authInfo != null
        ? AuthRouterApp(
            title: 'Plotting App',
            router: router,
            realm: authInfo.realm,
            clientId: authInfo.clientId,
            clientSecret: authInfo.clientSecret,
          )
        : NonAuthRouterApp(
            title: 'Plotting App',
            router: router,
          ),
    );
    return;
  }
  return runApp(appWidget);
}
